name: 'Build and release app'

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
      runs-on: windows-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@master

        - name: Install Node.js, NPM and Yarn
          uses: actions/setup-node@v1
          with:
            node-version: 18.15.0

        - name: Setup env
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}

        - name: Setup project
          - run: yarn

        - name: Apply version bump(major) then release app
          if: contains(github.event.pull_request.labels.*.name, 'major')
            run: npm version major
        - name: Apply version bump(minor) then release app
          if: contains(github.event.pull_request.labels.*.name, 'minor')
            run: npm version minor
        - name: Apply version bump(patch) then release app
          if: contains(github.event.pull_request.labels.*.name, 'patch')
            run: npm version patch